---
name: Actions
on: push
env: 
  WF_ENV: Disponible en todos los jobs

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: bash
        run: |
              ls -la
      - uses: actions/checkout@v2 # clona elo conteido del repositorio
      - name: bash
        run: |
              ls -la
      - name: Crear Archivo Random
        run: |
              echo $RANDOM >> random.txt
              git add random.txt
              git config --global user.email "misantam@example.com"
              git config --global user.name "Misantam"
              git commit -m "Añadido Random File"
              git push
