---
name: Game of life testing
on: push

jobs:
  game-of-life-test:
    runs-on: ubuntu-latest
    steps:
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: |
              java -version
              mvn --version
              git clone https://github.com/wakaleo/game-of-life.git .
              mvn test
