---

name: Comandos de shell
on: [push]

jobs:
  ejecutar-comandos-shell:
    runs-on: ubuntu-latest
    steps:
      - name: eccho cadena
        run: echo "Hello world"
      - name: scripts multilinea
        run: |
          node -v
          npm -v
          cat /etc/os-release
